from pymongo import MongoClient

# db mongodb://<dbuser>:<dbpassword>@ds047800.mongolab.com:47800/babyrockets
HOST = 'mongodb://chikka:chikka@ds047800.mongolab.com:47800/babyrockets'
MONGODB_PORT = 47800
DB_NAME = 'babyrockets'

CLIENT = MongoClient(HOST, MONGODB_PORT)
DB = CLIENT[DB_NAME]

# server
COOKIE_SERCRET = 'BASTA!SECRETNGAEH...'

# chikka api
CLIENT_ID = 'a0940c51555cac16f3de7ad57bd25a48530e68f91d6f3cf06e23b18d0031cc23'
SECRET_KEY = 'b1547d9cfe8765d8be048ca0ab9bb98f6559824cf69f47e9f8fbe976abf6e853'
SHORTCODE = 2929031337
REQUEST_COST = 'P2.50'


"""
FORMATS

Chikka().send(mobile_number, message {, message_id:, request_id:, request_cost:})
    message_id is autogenerated if not provided
    request_id is provided by sender

Sending:
    message_type: SEND
    mobile_number: 6391xxxxxxxx
    shortcode: 29290xxxxxx
    message_id: you need to generate. len = 32
    message: len <= 420
    client_id: provided by Chikka
    secret_key: provided by Chikka

Replying:
    message_type: REPLY
    mobile_number: 6391xxxxxxxx
    shortcode: 29290xxxxxx
    request_id: indicated in the message received from Chikka
    message_id: you need to generate. len = 32
    message: len <= 420
    request_cost:
        For SMART & Globe: FREE, P1.00, P2.50, P5.00, P10.00, P15.00
        For SUN: P2.00
    client_id: provided by Chikka
    secret_key: provided by Chikka

Delivery Notifications:
    message_type: outgoing
    shortcode: 29290xxxxxx
    message_id: from the message you sent
    status: SENT/FAILED
    credits_cost: amount deducted to your credits
    timestamp: time message was sent

Receiving:
    message_type: incoming
    mobile_number: 6391xxxxxxxx
    shortcode: 29290xxxxxx
    request_id: generated by sender
    message: len <= 420
    timestamp: time message was sent

when RECEVING MESSAGES or DELIVERY NOTIFICATIONS, a response is expected:
    Send an HTTP Post response (string): Accepted/Error

when SENDING or REPLYING, expect a response:
    1) Delivery notification; and
    2) HTTP Post response:
        200 ACCEPTED = Transaction has been successfully processed.
        400 BAD REQUEST	= Missing Required Fields: 
            Invalid Message ID
            Message Body Exceeded Allowed Length
            Insufficient Trial Credits
            Insufficient Credits
            Invalid/Used Request ID
            Inactive/Invalid Shortcode
            Invalid Message Type
        401 UNAUTHORIZED = Unauthorized access to the API; invalid access code or invalid signature.
        403 METHOD NOT ALLOWED = HTTP Request Method used was not POST.
        404 NOT FOUND = The URI being accessed is invalid or not available.
        500 ERROR = General system error

"""
